### ISSUE TITLE
$ gulp error

### ISSUE THREAD

**Issue by zanjs** [WRidder/react-spa#13]
$ gulp
[16:15:07] Warning: gulp version mismatch:
[16:15:07] Global gulp is 3.9.0
[16:15:07] Local gulp is 3.8.11
module.js:338
    throw err;
    ^

Error: Cannot find module './dependencies/TemplateArgumentDependency'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\zan\www\reactjs\react-spa\node_modules\webpack\lib\NormalModule.js:12:34)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by WRidder** [comment]
Hi, thanks for the heads up! The error is simply due to the out of date version of gulp in this repo. I have plans on updating this repo once I finished another project which should replace Reflux (the 'model' part of the app).
